### ISSUE TITLE
BE: User settings: Get & Post 06/23-06/24

### ISSUE THREAD

**Issue by stripes416** [Plantalytics/plantalytics-frontend#10]
**!!!!!**Possibly invalid, may be handled in-browser by frontend??**!!!!!**
Retrieving and returning user settings
- [ ] Build endpoint to retrieve user settings from the database transfer user settings to front end.
- [ ] Build endpoint to receive user settings from the front end and store in the database.

**Comment by kbrimm** [comment]
Is this something we still need?

**Comment by SoySauceLabs** [comment]
Negatory, this will be handled on the FE. "This" being "default env variable".
