### ISSUE TITLE
FE: Data selection

### ISSUE THREAD

**Issue by stripes416** [Plantalytics/plantalytics-frontend#14]
Add ability to select which data set to visualize

-- properly display heat map over the specified demo map. -- moved to FE#36
06/15/16 - 06/19/16
- [x] Add data selection (Leaf wetness, temperature, and humidity)
- [x] Properly display heat map overlay (with bounded edges)

-- Auto generate Heat map based on data selection -- moved to FE#36

**Comment by something15525** [comment]
Looks like there might need to be a bit more work on the backend side before moving forward on this ticket.

**Comment by SoySauceLabs** [comment]
Should be unblocked now that the backend is further along.
