### ISSUE TITLE
FE: User login and Authentication 06/20-06/22

### ISSUE THREAD

**Issue by stripes416** [Plantalytics/plantalytics-frontend#15]
Add user authentication methods for data protection and privacy.
06/20/16-06/22/16
- [ ] Account for demo vineyard
- [ ] Accept correct username / password combination
- [ ] Reject invalid username / password combination
- [ ] Display only data associated with accepted username / password

**Comment by something15525** [comment]
@SoySauceLabs we need to add an nginx config to fix the issue I've mentioned in FE#15 branch. 
This might be a start:
http://enable-cors.org/server_nginx.html

**Comment by something15525** [comment]
https://github.com/Plantalytics/plantalytics-backend/pull/20
and
https://github.com/Plantalytics/plantalytics-frontend/pull/34
