### ISSUE TITLE
DB: Set up Cassandra cluster 08/16/16

### ISSUE THREAD

**Issue by stripes416** [Plantalytics/plantalytics-frontend#16]
**!!!!!**_May stick to one node for MVP**_!!!!!**

Set up a two node cluster for our Cassandra DBMS.
~06/10/16-06/11/16~ moved to Final iteration
- [x] Link Bitnami account to Google Cloud Platform
- [ ] Set up two node cluster, with seed nodes (changed from three, per recommendations given to sponsors)
- [x] Deploy Bitnami Cassandra to cluster
- [ ] Verify gossip protocol is fully functional

**Comment by stripes416** [comment]
Half done, but I guess we're resetting the bar a bit.

**Comment by SoySauceLabs** [comment]
oh, lol, lemme move his back into the In Progress lane....

**Comment by kbrimm** [comment]
We're still shooting for at least a two-node cluster, right? The-little-node-that-could seems lonely. :(

**Comment by stripes416** [comment]
I don't think so, it wasn't a very high priority during the "priority" meeting

**Comment by SoySauceLabs** [comment]
Great question, I will defer to Kelly.... 👼

**Comment by SoySauceLabs** [comment]
That's funny we totally posted at the same moment....

**Comment by something15525** [comment]
Issue moved to [Plantalytics/plantalytics-backend #35](https://github.com/Plantalytics/plantalytics-backend/issues/35) via [**ZenHub**](https://www.zenhub.com/)
