### ISSUE TITLE
FE: Basic map interface

### ISSUE THREAD

**Issue by logicplace** [Plantalytics/plantalytics-frontend#21]
Basic map page interface. Does not need the heatmap immediately. This should make the map itself appear and have dummy buttons for changing the views and opening the menu.

Imagery and positioning etc for buttons should be selected purely by CSS as possible to allow for an alternate view for computers.
- [ ] Loads a satellite map image via Google Maps API
- [ ] Dummy buttons for view changes and the menu

**Comment by scotte216** [comment]
Graphically, looks nice and meets the requirements! I can't speak to the code as I don't know JS.

I only have 1 comment and 1 question, neither of which should prevent this from moving forward. 
1) In the settings pop-up in the lower right, it has 3 default views, a similar sized blank space, then log-out. What is the blank space for?
2) The settings pop-up in the lower right feels slow as it goes through the animation.

**Comment by something15525** [comment]
I found a bug. It seems like if you go directly to the dashboard, then use the "Logout" button in the settings, then login, then click settings again, the menu doesn't inflate.

**Comment by logicplace** [comment]
The blank space is this "I also added a temporary spacer to the menu so hopefully it looks a little less cramped overall?"

The menu can not inflate if there's a javascript error earlier, so check the developer console if that happens again. I'll make the method a little better to hopefully avoid that, though. I can speed up the animation at the same time.

**Comment by something15525** [comment]
alright, i'll take a look tonight

**Comment by logicplace** [comment]
Added #29 addressing those.

**Comment by something15525** [comment]
Here's a screenshot of the bug. The weird black rectangle is the inflated menu.

![inflation_bug](https://cloud.githubusercontent.com/assets/1452739/16214793/ad1afedc-3710-11e6-8a8c-6f64f0114491.png)

**Comment by something15525** [comment]
I totally put all the comments about the inflation but in #29 on accident.

**Comment by something15525** [comment]
No issues present in the console, besides a warning about google maps api:

util.js:211 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

**Comment by logicplace** [comment]
Which branch did you find that on? Shouldn't happen on #29 's

**Comment by something15525** [comment]
The ui bug or the api warning? Because I found both on #29

**Comment by logicplace** [comment]
The UI bug. API warning doesn't matter. I haven't been able to reproduce it though and there's really no reason it should happen on that branch. It happens when it doesn't know what the final height and width are, which is entirely unhelpful for why it might not know. There shouldn't be any reason why it both wouldn't know and still appear as 0px x 10px on that branch.

**Comment by something15525** [comment]
@logicplace I fixed the UI issue on #29, added a commit.

**Comment by scotte216** [comment]
I have re-checked this branch after the changes and now seem to get several errors. 

1) If I open the login page through my browser via drag-and-drop:
a - Log in
b - Next page displays "Oops! Something went wrong" with the following error in the console:
Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error_.ab @ js?callback=readyMap:35

2) If I launch the login through an IDE (PyCharm currently)
a - Log in
b - Map loads
There is no map overlay. Also, the 'gear' settings icon is similar to the screen shot above. 
![capture](https://cloud.githubusercontent.com/assets/13461180/16321454/cc8eb8f6-3951-11e6-83bb-96cb42a7ecd8.JPG)

**Comment by scotte216** [comment]
Apparently Google changed their requirements yesterday which probably accounts for these errors. 

[Google requirements](https://developers.google.com/maps/documentation/javascript/get-api-key?utm_source=geoblog&utm_medium=social&utm_campaign=2016-geo-na-website-gmedia-blogs-us-blogPost&utm_content=TBC)

Where does that leave this branch?

**Comment by kbrimm** [comment]
I vote we go ahead and merge this - Eric's item should fix the map issue, and I'm pretty sure his code piggybacks off this implementation. (Unless my understanding is incorrect.)

**Comment by kbrimm** [comment]
Wait! It's already merged. :facepalm: I'm going to close this ticket, then.
