### ISSUE TITLE
HW: Hub / Node Wake-ups 06/08-06/13

### ISSUE THREAD

**Issue by stripes416** [Plantalytics/plantalytics-frontend#4]
Hub wakes up nodes for data collection every 5 minutes
06/08/16-06/13/16
- [ ] Hub wakes up nodes
- [ ] Nodes return to "sleep"

**Comment by scotte216** [comment]
Is there any way to test this locally with perhaps an emulator? I don't have access to hardware and otherwise can only look at the code.

**Comment by something15525** [comment]
Issue moved to [Plantalytics/plantalytics-hardware #10](https://github.com/Plantalytics/plantalytics-hardware/issues/10) via [**ZenHub**](https://www.zenhub.com/)
