### ISSUE TITLE
Finalize APIs 07/22/16

### ISSUE THREAD

**Issue by stripes416** [Plantalytics/plantalytics-frontend#44]
- [ ] Error Handling
- [ ] Forgot Password
- [ ] Admin Page
- [ ] Multi-vineyard

**Comment by kbrimm** [comment]
This due date was yesterday. What's the word?

**Comment by logicplace** [comment]
Decided, just need to throw it into docs today.

**Comment by logicplace** [comment]
Multivineyard is just going to be downloaded with the login success packet. The rest is in the doc store in a new API folder. Admin pages aren't fully fleshed out but I don't expect them to be for a while honestly.

**Comment by SoySauceLabs** [comment]
Everything looks good to me!

**Comment by SoySauceLabs** [comment]
For those that haven't looked, the API doc is here:

**Project Documentation > Wiki+Reference > API > Basics**

**Comment by kbrimm** [comment]
Looks good to me as well. I'm hitting the button!
