### ISSUE TITLE
FE: Error Handling API implementation 08/02/16

### ISSUE THREAD

**Issue by stripes416** [Plantalytics/plantalytics-frontend#45]
- [x] Login interface displays error messages appropriately, allows user to correct.
- [x] Dashboard interface displays error messages appropriately.

**Comment by kbrimm** [comment]
This is due in two days - have you had a chance to start this, @stripes416?

**Comment by kbrimm** [comment]
Pushing due date to 08/02 to accommodate life. ;)

**Comment by stripes416** [comment]
Adding branch, let me know if I missed something :/
