### ISSUE TITLE
HW: Node / Hub data collection 06/12-06/15

### ISSUE THREAD

**Issue by stripes416** [Plantalytics/plantalytics-frontend#5]
Nodes gather data during "wake-ups" and transfer data to the hub.
06/12/16-06/15/16
- [ ] Nodes gather data
- [ ] Nodes transfer data to hub
- [ ] Nodes return to sleep

**Comment by kbrimm** [comment]
Blocked, waiting on sensors for data collection.

**Comment by kbrimm** [comment]
Moving to plantalytics-hardware.
