### ISSUE TITLE
FE: errors.js

### ISSUE THREAD

**Issue by logicplace** [Plantalytics/plantalytics-frontend#56]
Unified bit to handle response error parsing and display. My thoughts are to take in a jQuery object of an existing html element and .text display a string if there's only one and add a ul/li set of elements if there are more than one.

Maybe we want some sort of code->color type thing as well? Thoughts/suggestions welcome.

**Comment by stripes416** [comment]
I know @kbrimm flagged me on slack just after this was mentioned, but I have no idea what this is about. I'm a _bit_ out of the loop, so any / all explanation is welcome. Is it okay that I'm planning on just making a branch for #45, and adding whatever this is about to it if need be?

**Comment by SoySauceLabs** [comment]
I believe (could be wrong) this is for us to define the how we go about handling and displaying errors on the FE. This is kind of in a 'let's brainstorm implementation' stage. For example, perhaps we want a good 'ol bootstrap-style red "X" to display with our error messages. And, maybe we want the message to show up in a modal window. (in reference to Sapphire's question, I am all about color coding! :D)
