### ISSUE TITLE
HW: Hub sends data to backend 06/14-06/15

### ISSUE THREAD

**Issue by stripes416** [Plantalytics/plantalytics-frontend#6]
Hub sends batched data to the database.
06/14/16 - 06/15/16
- [ ] Hub batches the data collected
- [ ] Hub transfers data to the database

Data collection added to separate ticket 07/05.

**Comment by kbrimm** [comment]
Hub runs mLinux - http://www.multitech.net/developer/software/mlinux/mlinux-software-development/
Supports Python install - http://www.multitech.net/developer/software/mlinux/mlinux-software-development/python/
Data exchange from nodes should be brokered with Mosquitto - https://mosquitto.org/
Mosquitto has a Python module - https://pypi.python.org/pypi/paho-mqtt

**Comment by kbrimm** [comment]
On hold pending endpoint creation.

**Comment by kbrimm** [comment]
Changing to backend endpoint (Using Requests http://docs.python-requests.org/en/master/)

**Comment by kbrimm** [comment]
Moved to plantalytics-hardware.
